
-- Run this in your Supabase SQL Editor

-- Create Users Table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT DEFAULT 'member', -- 'admin', 'head', 'zonal_manager', 'member'
  zone TEXT,
  branch TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Create Daily Records Table
CREATE TABLE IF NOT EXISTS daily_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  date TEXT NOT NULL, -- YYYY-MM-DD
  morning_plan TEXT,
  actual_business NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Enable Row Level Security (RLS) if you want to restrict access via API directly
-- For this simple app using service role or just standard client in server-side API, 
-- we can keep it open or add policies.
-- Ideally, enable RLS and add policies.

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_records ENABLE ROW LEVEL SECURITY;

-- Allow public access for now (Simplest for your use case right now)
-- CAUTION: In production, you should restrict this.
CREATE POLICY "Enable all access for now" ON users FOR ALL USING (true);
CREATE POLICY "Enable all access for now records" ON daily_records FOR ALL USING (true);
