-- Create Monthly Targets Table
-- This table will store monthly targets and renewal statuses for each user/branch/zone.
-- We link it to 'users' via 'username' or 'id' for simplicity. Linking to 'id' is standard.
-- But the Excel might only have 'username'. So we'll need to look up IDs on insert.

CREATE TABLE IF NOT EXISTS monthly_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL, -- To easily map from Excel
    month TEXT NOT NULL, -- Format: 'YYYY-MM'
    
    -- Targets
    new_business_target NUMERIC DEFAULT 0,
    renewal_target NUMERIC DEFAULT 0,
    
    -- Achievements (Renewals collected so far)
    renewal_collected NUMERIC DEFAULT 0,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    
    -- Ensure user exists constraint? Ideally yes, but maybe targets uploaded before user signup?
    -- Let's keep it flexible for now, or enforce it. 
    -- Flexible is better for "pre-loading" targets.
    
    UNIQUE(username, month) -- Each user has one record per month
);

CREATE POLICY "Enable all access for now targets" ON monthly_targets FOR ALL USING (true);
ALTER TABLE monthly_targets ENABLE ROW LEVEL SECURITY;
