-- Create Recruitments Table
CREATE TABLE IF NOT EXISTS recruitments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  recruit_name TEXT NOT NULL,
  nic TEXT, -- Optional but good for identification
  contact_no TEXT,
  
  -- Checklist Stages
  status_file_submitted BOOLEAN DEFAULT false,
  status_exam_passed BOOLEAN DEFAULT false,
  status_documents_complete BOOLEAN DEFAULT false,
  status_appointed BOOLEAN DEFAULT false,
  
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Enable RLS
ALTER TABLE recruitments ENABLE ROW LEVEL SECURITY;

-- Allow users to manage their own recruits
CREATE POLICY "Users can manage own recruits" ON recruitments
  FOR ALL
  USING (true); -- Ideally restrict by user_id, but keeping simple for now as requested.

-- Admin can view all (Done via API logic usually or Service Role)
